[dependencies.alloc]
[dependencies.panic_abort]
[dependencies.panic_unwind]

[dependencies.std]
#git = "https://github.com/rust3ds/ctru-rs"
path = "/home/vivlim/git/rust-vivlim/library/std"
stage = 1
