name: Build 3ds Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Restore any cached docker layers
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build
      run: docker run --mount type=bind,source="$(pwd)",target=/build/app viviridian/3ds-rust-dkp:nightly-2021-01-30_v0 /bin/bash -c "cd /build/app && make"
    - name: Upload 3dsx artifact
      uses: actions/upload-artifact@v2
      with:
        name: 3dsx
        path: target/3ds/release/*.3dsx
